#pragma once
#include <cstdint>
#include <string>
#include <algorithm>
#include <cmath>
#include <random>
#include <cstdio>
#include "engine/core/types.h"

namespace fate {

// ============================================================================
// Class System
// ============================================================================
enum class ClassType : uint8_t {
    Warrior = 0,
    Mage = 1,
    Archer = 2,
    Any = 255
};

enum class ResourceType : uint8_t {
    None = 0,   // No resource cost (auto-attacks, passives)
    Fury = 1,   // Warriors/Archers - generated by attacks
    Mana = 2    // Mages - regenerates passively
};

// Class definition data (loaded from config, replaces Unity ScriptableObjects)
struct ClassDefinition {
    ClassType classType = ClassType::Warrior;
    std::string displayName = "Warrior";

    // Base stats at level 1
    int baseMaxHP = 120;
    int baseMaxMP = 40;
    int baseStrength = 12;
    int baseVitality = 12;
    int baseIntelligence = 8;
    int baseDexterity = 4;
    int baseWisdom = 8;

    // Combat stats at level 1
    float baseHitRate = 4.0f;
    float attackRange = 1.0f;

    // Resource system
    ResourceType primaryResource = ResourceType::Fury;
    int baseMaxFury = 3;
    int furyPerTenLevels = 1;
    float furyPerBasicAttack = 0.5f;
    float furyPerCriticalHit = 1.0f;
    float furyPerDamageReceived = 0.2f; // Warriors: 0.2, Rangers/Mages: 0.0

    // Per-level gains
    float hpPerLevel = 8.0f;
    float mpPerLevel = 3.0f;
    float strPerLevel = 1.5f;
    float vitPerLevel = 1.5f;
    float intPerLevel = 0.5f;
    float dexPerLevel = 0.8f;
    float wisPerLevel = 0.5f;

    int getMaxFuryForLevel(int level) const {
        if (primaryResource != ResourceType::Fury) return 0;
        return baseMaxFury + (level / 10) * furyPerTenLevels;
    }

    bool usesFury() const { return primaryResource == ResourceType::Fury; }
    bool usesMana() const { return primaryResource == ResourceType::Mana; }
};

// ============================================================================
// PK Status (PvP)
// ============================================================================
enum class PKStatus : uint8_t {
    White = 0,   // Innocent
    Purple = 1,  // Aggressor (1 min decay)
    Red = 2,     // Murderer (30 min decay)
    Black = 3    // Punished (10 min)
};

// ============================================================================
// Death Source — what killed the player (determines penalty type)
// ============================================================================
enum class DeathSource : uint8_t {
    PvE = 0,         // Killed by a mob → XP loss
    PvP = 1,         // Killed by another player → honor loss only
    Gauntlet = 2,    // Killed in Gauntlet → no penalties
    Environment = 3, // Killed by hazard/fall → XP loss (same as PvE)
    Battlefield = 4, // Killed in Battlefield event → no penalties
    Arena = 5,       // Killed in Arena match → no penalties
    Dungeon = 6,     // Killed in dungeon instance → no penalties
    Aurora = 7       // Killed in Aurora event → "Return to Town" only
};

// ============================================================================
// Equipment & Items
// ============================================================================
enum class EquipmentSlot : uint8_t {
    None = 0,
    Hat = 1,
    Armor = 2,
    Gloves = 3,
    Shoes = 4,
    Belt = 5,
    Cloak = 6,
    Weapon = 10,
    SubWeapon = 11,
    Ring = 20,
    Necklace = 21
};

inline bool isValidEquipmentSlot(uint8_t v) {
    switch (v) {
        case 0: case 1: case 2: case 3: case 4: case 5: case 6:
        case 10: case 11:
        case 20: case 21:
            return true;
        default:
            return false;
    }
}

enum class ItemRarity : uint8_t {
    Common = 0,
    Uncommon = 1,
    Rare = 2,
    Epic = 3,
    Legendary = 4,
    Unique = 5
};

inline ItemRarity parseItemRarity(const std::string& s) {
    if (s == "Uncommon")  return ItemRarity::Uncommon;
    if (s == "Rare")      return ItemRarity::Rare;
    if (s == "Epic")      return ItemRarity::Epic;
    if (s == "Legendary") return ItemRarity::Legendary;
    if (s == "Unique" || s == "Mythic") return ItemRarity::Unique;
    return ItemRarity::Common;
}

enum class ItemCategory : uint8_t {
    None = 0,
    Equipment = 1,
    Consumable = 2,
    Material = 3,
    Quest = 4,
    Bag = 5,
    Currency = 6,
    Misc = 99
};

// Flags enum
enum ClassRestriction : uint8_t {
    ClassRestriction_None = 0,
    ClassRestriction_Warrior = 1 << 0,
    ClassRestriction_Mage = 1 << 1,
    ClassRestriction_Archer = 1 << 2,
    ClassRestriction_All = ClassRestriction_Warrior | ClassRestriction_Mage | ClassRestriction_Archer
};

enum class StatType : uint8_t {
    // Primary stats
    Strength = 0,
    Intelligence = 1,
    Dexterity = 2,
    Vitality = 3,
    Wisdom = 4,
    // Health/Mana
    MaxHealth = 10,
    MaxMana = 11,
    HealthRegen = 12,
    ManaRegen = 13,
    // Attack stats
    PhysicalAttack = 20,
    MagicAttack = 21,
    AttackSpeed = 22,
    Accuracy = 23,
    // Defense stats
    PhysicalDefense = 30,
    MagicDefense = 31,
    Armor = 32,
    ArmorPierce = 33,
    BlockChance = 34,
    Evasion = 35,
    // Critical
    CriticalChance = 40,
    CriticalDamage = 41,
    // Movement
    MoveSpeed = 50,
    // Special
    Lifesteal = 60,
    ExecuteThreshold = 61,
    ExecuteDamageBonus = 62,
    // Elemental
    FireResist = 70,
    WaterResist = 71,
    PoisonResist = 72,
    LightningResist = 73,
    VoidResist = 74,
    MagicResist = 75
};

enum class ElementType : uint8_t {
    None = 0,
    Physical = 1,
    Fire = 2,
    Water = 3,
    Poison = 4,
    Lightning = 5,
    Void = 6,
    Magic = 7
};

// ============================================================================
// Combat
// ============================================================================
enum class EffectType : uint8_t {
    Bleed = 0, Burn, Poison,
    Slow, ArmorShred, HuntersMark,
    AttackUp, ArmorUp, SpeedUp, ManaRegenUp,
    Shield, Invulnerable, StunImmune, GuaranteedCrit,
    Transform,
    Bewitched,
    ExpGainUp,
    COUNT_ // keep last — used by static_assert below
};
static_assert(static_cast<int>(EffectType::COUNT_) <= 32,
              "EffectType count exceeds 32; widen effect bitmask type");

enum class CCType : uint8_t {
    None = 0,
    Stunned = 1,
    Frozen = 2,
    Rooted = 3,
    Taunted = 4
};

// ============================================================================
// Hit Flags (bitmask for SvSkillResult)
// ============================================================================
namespace HitFlags {
    constexpr uint8_t HIT      = 1 << 0;
    constexpr uint8_t CRIT     = 1 << 1;
    constexpr uint8_t MISS     = 1 << 2;
    constexpr uint8_t DODGE    = 1 << 3;
    constexpr uint8_t BLOCKED  = 1 << 4;
    constexpr uint8_t ABSORBED = 1 << 5;
    constexpr uint8_t KILLED   = 1 << 6;
}

enum class FaceDirection : uint8_t {
    Down = 0,
    Up = 1,
    Left = 2,
    Right = 3
};

enum class TargetType : uint8_t {
    None = 0,
    Mob = 1,
    Boss = 2,
    NPC = 3,
    Player = 4,
    PvPPlayer = 5,
    PartyMember = 6,
    GuildMember = 7
};

// ============================================================================
// Skills
// ============================================================================
enum class SkillType : uint8_t {
    Active = 0,
    Passive = 1
};

enum class SkillTargetType : uint8_t {
    Self = 0,
    SingleEnemy = 1,
    SingleAlly = 2,
    AreaAroundSelf = 3,
    AreaAtTarget = 4,
    Cone = 5,
    Line = 6
};

enum class DamageType : uint8_t {
    Physical = 0,
    Magic = 1,
    Fire = 2,
    Water = 3,
    Lightning = 4,
    Poison = 5,
    Void = 6,
    True = 7  // Ignores all defenses
};

// ============================================================================
// Social
// ============================================================================
enum class ChatChannel : uint8_t {
    Map = 0, Global, Trade, Party, Guild, Private, System
};

// ============================================================================
// Admin Roles
// ============================================================================
enum class AdminRole : int { Player = 0, GM = 1, Admin = 2 };

enum class PartyLootMode : uint8_t {
    FreeForAll = 0,
    Random = 1
};

enum class GuildRank : uint8_t {
    Member = 0,
    Officer = 1,
    Owner = 2
};

// ============================================================================
// Rarity Colors (matching TWOM style)
// ============================================================================
namespace RarityColors {
    inline Color getColor(ItemRarity rarity) {
        switch (rarity) {
            case ItemRarity::Common:    return Color::white();
            case ItemRarity::Uncommon:  return {0.290f, 0.871f, 0.502f};
            case ItemRarity::Rare:      return {0.376f, 0.647f, 0.980f};
            case ItemRarity::Epic:      return {0.659f, 0.333f, 0.969f};
            case ItemRarity::Legendary: return {0.984f, 0.573f, 0.235f};
            case ItemRarity::Unique:    return {0.937f, 0.267f, 0.267f};
            default: return Color::white();
        }
    }
}

// ============================================================================
// Mob Level Colors (TWOM-style nameplate coloring)
// ============================================================================
namespace MobLevelColors {
    constexpr int TRIVIAL_THRESHOLD = -3;
    constexpr int MAX_DANGER_LEVEL = 4;

    inline Color getColor(int mobLevel, int playerLevel) {
        int diff = mobLevel - playerLevel;
        if (diff <= TRIVIAL_THRESHOLD) return {0.5f, 0.5f, 0.5f};   // Gray
        if (diff < 0)  return {0.290f, 0.871f, 0.502f};              // Green
        if (diff == 0) return Color::white();
        switch (diff) {
            case 1: return {0.376f, 0.647f, 0.980f};  // Blue
            case 2: return {0.659f, 0.333f, 0.969f};  // Purple
            case 3: return {0.984f, 0.573f, 0.235f};  // Orange
            default: return {0.937f, 0.267f, 0.267f}; // Red
        }
    }

    inline bool isTrivial(int mobLevel, int playerLevel) {
        return (mobLevel - playerLevel) <= TRIVIAL_THRESHOLD;
    }
}

// ============================================================================
// Character Constants
// ============================================================================
namespace CharacterConstants {
    constexpr int MAX_PLAYER_LEVEL = 200;
    constexpr int MAX_STAT_BONUS = INT16_MAX;  // 32767 — overflow guard for equipment stacking
}

// ============================================================================
// Inventory Constants
// ============================================================================
namespace InventoryConstants {
    constexpr int BASE_INVENTORY_SLOTS = 16;
    constexpr int64_t MAX_GOLD = 999'999'999LL;
    constexpr int MAX_STACK_SIZE = 9999;
}

// ============================================================================
// Trade Constants
// ============================================================================
namespace TradeConstants {
    constexpr int MAX_TRADE_SLOTS = 8;
    constexpr float INVITE_TIMEOUT_SECONDS = 30.0f;
    constexpr float MAX_TRADE_DISTANCE = 5.0f;
}

// ============================================================================
// Market Constants
// ============================================================================
namespace MarketConstants {
    constexpr int MAX_LISTINGS_PER_PLAYER = 7;
    constexpr int LISTING_DURATION_HOURS = 48;
    constexpr float TAX_RATE = 0.02f;
    constexpr int JACKPOT_INTERVAL_HOURS = 2;
    constexpr int64_t MAX_LISTING_PRICE = 999'999'999LL;
}

// ============================================================================
// Chat Constants
// ============================================================================
namespace ChatConstants {
    constexpr int MAX_MESSAGE_LENGTH = 200;
    constexpr float RATE_LIMIT_SECONDS = 0.5f;
    constexpr int MAX_CHAT_HISTORY = 100;
    constexpr float PROXIMITY_RANGE = 15.0f;
}

// ============================================================================
// Guild Constants
// ============================================================================
namespace GuildConstants {
    constexpr int CREATION_COST = 100000;
    constexpr int DEFAULT_MAX_MEMBERS = 20;
    constexpr int MAX_OFFICERS = 5;
    constexpr int SYMBOL_SIZE = 16;
    constexpr int TOTAL_PIXELS = 256;
    constexpr int PALETTE_SIZE = 16;
}

// ============================================================================
// PK Cooldowns
// ============================================================================
namespace PKCooldowns {
    constexpr float RED_TO_WHITE_SECONDS = 1800.0f;   // 30 min
    constexpr float BLACK_TO_WHITE_SECONDS = 600.0f;   // 10 min
    constexpr float PURPLE_DECAY_SECONDS = 60.0f;      // 1 min
}

// ============================================================================
// Enchantment Constants
// ============================================================================
namespace EnchantConstants {
    constexpr int MAX_ENCHANT_LEVEL = 15;
    constexpr int SAFE_ENCHANT_LEVEL = 8;
}

// ============================================================================
// XP Formula
// ============================================================================
inline int64_t calculateXPToNextLevel(int level) {
    int64_t val = static_cast<int64_t>(std::round(0.35 * std::pow(level, 5.1)));
    return val > 100 ? val : 100;
}

// ============================================================================
// UUID v4 generation for item instance IDs
// ============================================================================
inline std::string generateItemInstanceId() {
    static thread_local std::mt19937_64 rng(std::random_device{}());
    std::uniform_int_distribution<uint64_t> dist;
    uint64_t hi = dist(rng);
    uint64_t lo = dist(rng);
    // Set version 4 (bits 12-15 of time_hi_and_version)
    hi = (hi & 0xFFFFFFFFFFFF0FFFULL) | 0x0000000000004000ULL;
    // Set variant 1 (bits 6-7 of clk_seq_hi_res)
    lo = (lo & 0x3FFFFFFFFFFFFFFFULL) | 0x8000000000000000ULL;
    char buf[37];
    std::snprintf(buf, sizeof(buf),
        "%08x-%04x-%04x-%04x-%012llx",
        static_cast<uint32_t>(hi >> 32),
        static_cast<uint16_t>((hi >> 16) & 0xFFFF),
        static_cast<uint16_t>(hi & 0xFFFF),
        static_cast<uint16_t>(lo >> 48),
        static_cast<unsigned long long>(lo & 0x0000FFFFFFFFFFFFULL));
    return std::string(buf);
}

// ============================================================================
// Replication Visual Encoding
// ============================================================================
enum class MoveState : uint8_t {
    Idle    = 0,
    Walking = 1
};

// Map engine Direction to 3-direction animDir (down=0, up=1, side=2)
inline uint8_t facingToAnimDir(Direction facing) {
    switch (facing) {
        case Direction::Down:  return 0;
        case Direction::Up:    return 1;
        case Direction::Left:  return 2;
        case Direction::Right: return 2;
        case Direction::None:  return 0;
    }
    return 0;
}

// Encode: animId = animDir * 4 + animType
// animType: 0=idle, 1=walk, 2=attack, 3=cast
// Special: 12 = death
inline uint16_t encodeAnimId(uint8_t animDir, uint8_t animType) {
    return static_cast<uint16_t>(animDir * 4 + animType);
}

// Decode animId → animDir (0-2) and animType (0-3)
inline void decodeAnimId(uint16_t animId, uint8_t& animDir, uint8_t& animType) {
    if (animId == 12) { animDir = 0; animType = 4; return; } // death special case
    animDir  = static_cast<uint8_t>(animId / 4);
    animType = static_cast<uint8_t>(animId % 4);
}

// Pack 3 equipment visual indices (10 bits each) into uint32
inline uint32_t packEquipVisuals(uint16_t weaponIdx, uint16_t armorIdx, uint16_t hatIdx) {
    return (static_cast<uint32_t>(weaponIdx) & 0x3FF)
         | ((static_cast<uint32_t>(armorIdx)  & 0x3FF) << 10)
         | ((static_cast<uint32_t>(hatIdx)    & 0x3FF) << 20);
}

// Unpack uint32 → 3 visual indices
inline void unpackEquipVisuals(uint32_t packed, uint16_t& weaponIdx, uint16_t& armorIdx, uint16_t& hatIdx) {
    weaponIdx = static_cast<uint16_t>(packed & 0x3FF);
    armorIdx  = static_cast<uint16_t>((packed >> 10) & 0x3FF);
    hatIdx    = static_cast<uint16_t>((packed >> 20) & 0x3FF);
}

// Pack 6 costume visual indices (10 bits each) into uint64
inline uint64_t packCostumeVisuals(uint16_t weapon, uint16_t armor, uint16_t hat,
                                    uint16_t shield, uint16_t gloves, uint16_t boots) {
    return (static_cast<uint64_t>(weapon)  & 0x3FF)
         | ((static_cast<uint64_t>(armor)  & 0x3FF) << 10)
         | ((static_cast<uint64_t>(hat)    & 0x3FF) << 20)
         | ((static_cast<uint64_t>(shield) & 0x3FF) << 30)
         | ((static_cast<uint64_t>(gloves) & 0x3FF) << 40)
         | ((static_cast<uint64_t>(boots)  & 0x3FF) << 50);
}

// Unpack uint64 -> 6 costume visual indices
inline void unpackCostumeVisuals(uint64_t packed,
                                  uint16_t& weapon, uint16_t& armor, uint16_t& hat,
                                  uint16_t& shield, uint16_t& gloves, uint16_t& boots) {
    weapon = static_cast<uint16_t>(packed & 0x3FF);
    armor  = static_cast<uint16_t>((packed >> 10) & 0x3FF);
    hat    = static_cast<uint16_t>((packed >> 20) & 0x3FF);
    shield = static_cast<uint16_t>((packed >> 30) & 0x3FF);
    gloves = static_cast<uint16_t>((packed >> 40) & 0x3FF);
    boots  = static_cast<uint16_t>((packed >> 50) & 0x3FF);
}

} // namespace fate
